import {
  APP_ENV,
  API_BASE_URL,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  AWS_REGION,
  AWS_USER_POOL_ID,
  AWS_USER_POOL_CLIENT_ID,
  STRIPE_PUBLISHABLE_KEY,
  STRIPE_MERCHANT_IDENTIFIER,
} from '@env';

const sanitize = value => {
  if (typeof value !== 'string') {
    return '';
  }

  const trimmed = value.trim();
  return trimmed.replace(/^['"]|['"]$/g, '');
};

export const ENV = {
  APP_ENV: sanitize(APP_ENV),
  API_BASE_URL: sanitize(API_BASE_URL),

  FIREBASE_API_KEY: sanitize(FIREBASE_API_KEY),
  FIREBASE_AUTH_DOMAIN: sanitize(FIREBASE_AUTH_DOMAIN),
  FIREBASE_PROJECT_ID: sanitize(FIREBASE_PROJECT_ID),
  FIREBASE_STORAGE_BUCKET: sanitize(FIREBASE_STORAGE_BUCKET),
  FIREBASE_MESSAGING_SENDER_ID: sanitize(FIREBASE_MESSAGING_SENDER_ID),
  FIREBASE_APP_ID: sanitize(FIREBASE_APP_ID),

  AWS_REGION: sanitize(AWS_REGION),
  AWS_USER_POOL_ID: sanitize(AWS_USER_POOL_ID),
  AWS_USER_POOL_CLIENT_ID: sanitize(AWS_USER_POOL_CLIENT_ID),

  STRIPE_PUBLISHABLE_KEY: sanitize(STRIPE_PUBLISHABLE_KEY),
  STRIPE_MERCHANT_IDENTIFIER: sanitize(STRIPE_MERCHANT_IDENTIFIER),
};

export const REQUIRED_ENV_KEYS = [
  'APP_ENV',
  'API_BASE_URL',
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'AWS_REGION',
  'AWS_USER_POOL_ID',
  'AWS_USER_POOL_CLIENT_ID',
  'STRIPE_PUBLISHABLE_KEY',
  'STRIPE_MERCHANT_IDENTIFIER',
];
